### ISSUE TITLE
Higher Sig Figs in Output file

### ISSUE THREAD

**Issue by Nikhil0504** [cschreib/fastpp#19]
Hey, How do you get higher significant figures for your output columns? Can you add a feature where we can define that?

**Comment by cschreib** [comment]
Hi there! This was not currently configurable, but fairly easy to add. The [latest commit on the master branch](https://github.com/cschreib/fastpp/commit/3fc080a93b933f66cdd73fce4e1aafdc716a28ac) has the `OUTPUT_PRECISION` option; default is zero (which means "same as before"), otherwise pick the precision you want (e.g., `1e-6`). See the docs for more info. Please let me know if this does what you want, and I can then close this issue. Cheers.

Edit: Actually that commit was still limited to a max precision of 1e-6; this is now fixed in https://github.com/cschreib/fastpp/commit/0c68bbbfb983f012375cb6555c5b545df87ad20a.

**Comment by Nikhil0504** [comment]
Hey! Thanks for the update.. this is exactly what I wanted.

I am closing this issue.
