### ISSUE TITLE
custom SFH as a piecewise constant model

### ISSUE THREAD

**Issue by camlawlorforsyth** [cschreib/fastpp#20]
Hi, I'm wondering if it's possible to define a custom SFH using something similar to the piecewise constant model of [Leja et al. 2019](https://ui.adsabs.harvard.edu/abs/2019ApJ...876....3L/abstract), section 2.1 and 2.2.1. Essentially the SFH is parameterized as a series of uncorrelated "bursts" with fixed time edges, where the SFR is constant between those time edges, creating a kind of step function.

Reading the available documentation, I'm not sure how I could go about doing this, as the SFR isn't exactly described by a smoothly varying function of time.

Any insight or help would be appreciated!

**Comment by cschreib** [comment]
Hi! As you noticed, the custom SFH model in FAST++ is geared towards continuous functions. However it is indeed possible, albeit a bit convoluted. I haven't had the chance to actually test it, but the idea would be to use something like this:
```
CUSTOM_SFH_LOOKBACK = 1  # turn on "t = lookback time" to keep the expression simpler
CUSTOM_PARAMS       = ['r0','r1','r2','r3','r4','r5','r6']
CUSTOM_SFH          = '(t <= 3e7)*r0 + (t > 3e7 && t <= 1e8)*r1 + (t > 1e8 && t <= 3.3e8)*r2 + (t > 3.3e8 && t <= 1.1e9)*r3 + (t > 1.1e9 && t <= 3.6e9)*r4 + (t > 3.6e9 && t <= 1.17e10)*r5 + (t > 1.17e10)*r6'
R0_MIN              = 0
R0_MAX              = 1
R0_STEP             = 0.1
R1_MIN              = 0
R1_MAX              = 1
R1_STEP             = 0.1
R2_MIN              = 0
R2_MAX              = 1
R2_STEP             = 0.1
R3_MIN              = 0
R3_MAX              = 1
R3_STEP             = 0.1
R4_MIN              = 0
R4_MAX              = 1
R4_STEP             = 0.1
R5_MIN              = 0
R5_MAX              = 1
R5_STEP             = 0.1
R6_MIN              = 0
R6_MAX              = 1
R6_STEP             = 0.1
```

The trick is to use `(t > a && t <= b)` (which produces `1` if `t` is within `a` and `b`, and `0` otherwise) to select different functions. Here the "function" is just a parameterized constant `r0` (or `r1`, ...), which generates your step function. Since FAST++ is a brute-force solver, it needs to define a grid, so you have to set the min/max bounds for all the `r0`, `r1`, etc., and choose the size of the parameter step in the grid. Here I picked `0.1`, which gives you 10 different values for each bin. Combined, this produces a total of 20 million model SFHs, so it adds up pretty quickly... 

But you can then tune this however you like, for example having a finer step in `r0` than in `r6` to allow for a finer adjustment of the more recent SFH. You can also use logarithmic steps by changing `(t > a && t <= b)*r0` into `(t > a && t <= b)*10^r0`, and then changing `R0_MIN=-4`, `R0_MAX=0`, `R0_STEP=0.4`. All up to you!

**Comment by camlawlorforsyth** [comment]
Hi Corentin, thanks very much for your quick response! I've successfully implemented your parameterization, and am getting results that make sense based on what I expect.

As far as setting up an efficient grid, do you have any suggestions for the parameters that are always included, ie. `lage` and `A_V`? I know I can select a smaller value for the upper limit on the extinction, for example 3 magnitudes instead of 6, but I'm curious if you have experience with using a sparser grid for `lage`?

As you noted above, using a grid with enough resolution produces a very large parameter space, so I'm trying to think about ways to optimize my grid, or even using a hybrid approach like a delay tau model up until 100 Myr ago, and then using a burst with `r0` for the most recent 100 Myr, for example.

Thanks for your time,
Cam

**Comment by cschreib** [comment]
For `lage`, my recommendation would be to just fix it to the age of the universe at the redshift of your galaxy (assuming you are only fitting one galaxy at a time, which is what I ended up doing in my papers). Your star formation history is flexible enough to have zero SFR at earlier times, effectively producing a younger galaxy without changing `lage`. Hence the age parameter is not necessary. 

For `A_V`, indeed `6` is a very conservative number, and `3` is probably fine as an upper limit for 99% of the cases. Whether this is safe for you or not depends on the specific cases you are modeling. By reducing the size of the grid you are effectively adding prior "knowledge" to the fit (i.e., this galaxy is not an extremely obscured object). You just need to be conscious of this, have some idea of confidence in this "knowledge", and ideally understand what the consequence would be if this "knowledge" turns out to be incorrect. A useful approach there is to do a first fit with a wide but coarse grid, to get a feel for the range of plausible solutions. If all the solutions in this first step have `A_V < 1`, you're probably safe with a maximum of `2`, for example. Then you can rerun the fit with a finer grid, etc.

For the hybrid approach, this is what we used in [one of my papers](https://ui.adsabs.harvard.edu/abs/2018A%26A...618A..85S/abstract), inspired from [work from a collaborator](https://ui.adsabs.harvard.edu/abs/2016A%26A...585A..43C/abstract). This is a cheap way to give a lot of freedom to your star formation histories, and avoid the common pitfalls of purely continuous models. However, regardless what of what option you choose, I would always recommend against interpreting the SFH parameters directly, and instead would recommend computing "non-parameteric" properties (as was done in that first paper).

**Comment by camlawlorforsyth** [comment]
Great! Thank you very much for all of your insight and suggestions, this has been very helpful!

**Comment by camlawlorforsyth** [comment]
I have another question as a quick follow-up:

I'm trying to implement the hyrbid model that I mentioned above, but I don't think I have the expression completely correct. I think the normalisation (`lscale`?) might be influencing my results.

Here's what I was using:
```
CUSTOM_SFH          = '(t <= 1e8)*10^r0 + (t > 1e8)*((10^lage - t)/10^log_tau)*exp(-((10^lage - t)/10^log_tau))'
CUSTOM_PARAMS       = ['r0', 'log_tau']
CUSTOM_SFH_LOOKBACK = 1
R0_MIN              = -3
R0_MAX              = 2
R0_STEP             = 0.25
```

I think the issue may lie in that the normalisation is being applied to the entire expression, but while `r0` is effectively in (log) physical units, the delayed tau component in general won't have the same normalisation, but obviously I can't seperate the components.

I think I'm simply after the SFH model of Ciesla et al. 2016, but I'm not sure how to access the SFR at a given time (e.g., 100 Myr ago, or t=t_trunc in the case of Ciesla et al.) but simultaneously include it in the general expression for the SFH.

Thanks!

**Comment by cschreib** [comment]
Suppose you have this expression for the continuous SFH model: `exp(t/10^ltau)`. You can modulate this by multiplying by another expression, `exp(t/10^ltau)*(...)`.

You can use the same trick as above to modulate this with a discontinuous function. For example `(t > 1e8) + (t <= 1e8)*10^lrsfr`; this is a function that is equal to 1 for earlier ages, and `10^lrsfr` in the last 100Myr. The parameter `lrsfr` lets you control (in log scale) the relative decrease or increase of the SFR in the past 100Myr.

You can't otherwise access the "current SFR", or the SFR at other times, because this mathematical expression is what creates it; it would lead to a circular reference. Simply write down what the math expression would be, replacing any reference to the SFR by its actual mathematical expression. It can lead to quite lengthy SFH functions, but there is no other way.
